// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: om.proto3

package core;


public final class WebsiteDataProto {
  private WebsiteDataProto() {}
  public static void registerAllExtensions(
      google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface websiteDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.websiteData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string ipAddress = 2;</code>
     */
    boolean hasIpAddress();
    /**
     * <code>required string ipAddress = 2;</code>
     */
    java.lang.String getIpAddress();
    /**
     * <code>required string ipAddress = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    /**
     * <code>required int32 levelOfDomain = 3;</code>
     */
    boolean hasLevelOfDomain();
    /**
     * <code>required int32 levelOfDomain = 3;</code>
     */
    int getLevelOfDomain();
  }
  /**
   * Protobuf type {@code core.websiteData}
   */
  public  static final class websiteData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.websiteData)
      websiteDataOrBuilder {
    // Use websiteData.newBuilder() to construct.
    private websiteData(google.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private websiteData() {
      name_ = "";
      ipAddress_ = "";
      levelOfDomain_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private websiteData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          google.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ipAddress_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              levelOfDomain_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.WebsiteDataProto.internal_static_core_websiteData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.WebsiteDataProto.internal_static_core_websiteData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.WebsiteDataProto.websiteData.class, core.WebsiteDataProto.websiteData.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            google.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IPADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object ipAddress_;
    /**
     * <code>required string ipAddress = 2;</code>
     */
    public boolean hasIpAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ipAddress = 2;</code>
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ipAddress = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            google.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVELOFDOMAIN_FIELD_NUMBER = 3;
    private int levelOfDomain_;
    /**
     * <code>required int32 levelOfDomain = 3;</code>
     */
    public boolean hasLevelOfDomain() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 levelOfDomain = 3;</code>
     */
    public int getLevelOfDomain() {
      return levelOfDomain_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevelOfDomain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        google.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        google.GeneratedMessageV3.writeString(output, 2, ipAddress_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, levelOfDomain_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += google.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += google.GeneratedMessageV3.computeStringSize(2, ipAddress_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += google.CodedOutputStream
          .computeInt32Size(3, levelOfDomain_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.WebsiteDataProto.websiteData)) {
        return super.equals(obj);
      }
      core.WebsiteDataProto.websiteData other = (core.WebsiteDataProto.websiteData) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasIpAddress() == other.hasIpAddress());
      if (hasIpAddress()) {
        result = result && getIpAddress()
            .equals(other.getIpAddress());
      }
      result = result && (hasLevelOfDomain() == other.hasLevelOfDomain());
      if (hasLevelOfDomain()) {
        result = result && (getLevelOfDomain()
            == other.getLevelOfDomain());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasIpAddress()) {
        hash = (37 * hash) + IPADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getIpAddress().hashCode();
      }
      if (hasLevelOfDomain()) {
        hash = (37 * hash) + LEVELOFDOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + getLevelOfDomain();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.WebsiteDataProto.websiteData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.WebsiteDataProto.websiteData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.WebsiteDataProto.websiteData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.WebsiteDataProto.websiteData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.WebsiteDataProto.websiteData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return google.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.WebsiteDataProto.websiteData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return google.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.WebsiteDataProto.websiteData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return google.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.WebsiteDataProto.websiteData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return google.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.WebsiteDataProto.websiteData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return google.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.WebsiteDataProto.websiteData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return google.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.WebsiteDataProto.websiteData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.websiteData}
     */
    public static final class Builder extends
        google.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.websiteData)
        core.WebsiteDataProto.websiteDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.WebsiteDataProto.internal_static_core_websiteData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.WebsiteDataProto.internal_static_core_websiteData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.WebsiteDataProto.websiteData.class, core.WebsiteDataProto.websiteData.Builder.class);
      }

      // Construct using core.WebsiteDataProto.websiteData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (google.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ipAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        levelOfDomain_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.WebsiteDataProto.internal_static_core_websiteData_descriptor;
      }

      public core.WebsiteDataProto.websiteData getDefaultInstanceForType() {
        return core.WebsiteDataProto.websiteData.getDefaultInstance();
      }

      public core.WebsiteDataProto.websiteData build() {
        core.WebsiteDataProto.websiteData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public core.WebsiteDataProto.websiteData buildPartial() {
        core.WebsiteDataProto.websiteData result = new core.WebsiteDataProto.websiteData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ipAddress_ = ipAddress_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.levelOfDomain_ = levelOfDomain_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.WebsiteDataProto.websiteData) {
          return mergeFrom((core.WebsiteDataProto.websiteData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.WebsiteDataProto.websiteData other) {
        if (other == core.WebsiteDataProto.websiteData.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasIpAddress()) {
          bitField0_ |= 0x00000002;
          ipAddress_ = other.ipAddress_;
          onChanged();
        }
        if (other.hasLevelOfDomain()) {
          setLevelOfDomain(other.getLevelOfDomain());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasIpAddress()) {
          return false;
        }
        if (!hasLevelOfDomain()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        core.WebsiteDataProto.websiteData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (core.WebsiteDataProto.websiteData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              google.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ipAddress_ = "";
      /**
       * <code>required string ipAddress = 2;</code>
       */
      public boolean hasIpAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ipAddress = 2;</code>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipAddress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ipAddress = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              google.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ipAddress = 2;</code>
       */
      public Builder setIpAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ipAddress = 2;</code>
       */
      public Builder clearIpAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ipAddress_ = getDefaultInstance().getIpAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string ipAddress = 2;</code>
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ipAddress_ = value;
        onChanged();
        return this;
      }

      private int levelOfDomain_ ;
      /**
       * <code>required int32 levelOfDomain = 3;</code>
       */
      public boolean hasLevelOfDomain() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 levelOfDomain = 3;</code>
       */
      public int getLevelOfDomain() {
        return levelOfDomain_;
      }
      /**
       * <code>required int32 levelOfDomain = 3;</code>
       */
      public Builder setLevelOfDomain(int value) {
        bitField0_ |= 0x00000004;
        levelOfDomain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 levelOfDomain = 3;</code>
       */
      public Builder clearLevelOfDomain() {
        bitField0_ = (bitField0_ & ~0x00000004);
        levelOfDomain_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.websiteData)
    }

    // @@protoc_insertion_point(class_scope:core.websiteData)
    private static final core.WebsiteDataProto.websiteData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.WebsiteDataProto.websiteData();
    }

    public static core.WebsiteDataProto.websiteData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final google.Parser<websiteData>
        PARSER = new google.AbstractParser<websiteData>() {
      public websiteData parsePartialFrom(
          google.CodedInputStream input,
          google.ExtensionRegistryLite extensionRegistry)
          throws google.InvalidProtocolBufferException {
          return new websiteData(input, extensionRegistry);
      }
    };

    public static google.Parser<websiteData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public google.Parser<websiteData> getParserForType() {
      return PARSER;
    }

    public core.WebsiteDataProto.websiteData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_websiteData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_websiteData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tom.proto3\022\004core\"E\n\013websiteData\022\014\n\004name" +
      "\030\001 \002(\t\022\021\n\tipAddress\030\002 \002(\t\022\025\n\rlevelOfDoma" +
      "in\030\003 \002(\005B\022B\020WebsiteDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    google.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_core_websiteData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_websiteData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_websiteData_descriptor,
        new java.lang.String[] { "Name", "IpAddress", "LevelOfDomain", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
